[package]
name = "vectored-mtvec"
version = "0.1.0"
edition = "2024"
license = "MIT"

[[bin]]
name = "vectored-mtvec"
path = "main.rs"

[lints]
workspace = true

[dependencies]
miralis_abi = { path = "../../crates/abi" }
test_helpers = { path = "../../crates/test_helpers" }
log = { workspace = true }
