# NOTE: Unfortunately we loose the ability to use unstable formatting options
# by moving to a stable compiler version. We should strive to maintain the current
# code style until the options are stabilized.
#
# unstable_features   = true
# imports_granularity = "Module"
# group_imports       = "StdExternalCrate"
