[package]
name = "mirage"
version = "0.1.0"
edition = "2021"

[dependencies]
uart_16550 = "0.3.0"
spin = "0.5.2"
log = { workspace = true }
mirage_core = { path = "crates/core" }

[features]
host = [] # When running on host architecture, such as when running unit tests.

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[workspace]
members = [
    # Payloads
    "payloads/csr_ops",
    "payloads/default",
    "payloads/ecall",
    "payloads/mscratch",
    "payloads/pmp",
    "payloads/perf_monitor",
    "payloads/menv_msec",
    "payloads/breakpoint",
    "payloads/mepc",
    "payloads/mcause",
    "payloads/mconfigptr",
    "payloads/mret",
    "payloads/misa",

    # Crates
    "crates/abi",
    "crates/core",

    # Tooling
    "runner",
]

[workspace.dependencies]
log = "0.4.17"
