[package]
name = "miralis"
version = "0.1.0"
edition = "2021"

[dependencies]
uart_16550 = "0.3.0"
spin = "0.5.2"
log = { workspace = true }
miralis_core = { path = "crates/core" }

[features]
# When running on host architecture as a userspace application, such as when
# running unit tests.
userspace = []
platform_visionfive2 = []

[profile.dev]
panic = "abort"
opt-level = 3

[profile.release]
panic = "abort"

[workspace]
members = [
    # Firmware
    "firmware/csr_ops",
    "firmware/default",
    "firmware/ecall",
    "firmware/pmp",
    "firmware/breakpoint",
    "firmware/mepc",
    "firmware/mcause",
    "firmware/mret",
    "firmware/os_ctx_switch",
    "firmware/sandbox",
    "firmware/interrupt",

    # Crates
    "crates/abi",
    "crates/core",

    # Tooling
    "runner", "benchmark-analyzer",
]

[workspace.dependencies]
log = "0.4.17"
