[package]
name = "mirage"
version = "0.1.0"
edition = "2021"

[dependencies]
uart_16550 = "0.3.0"
spin = "0.5.2"
log = "0.4.17"

[workspace]
members = [
    # Payloads
    "payloads/csr_ops",
    "payloads/default",
    "payloads/ecall",
    "payloads/mscratch",
    "payloads/csr_id",
    "payloads/pmp",
    "payloads/perf_monitor",

    # Crates
    "crates/mirage_abi",

    # Tooling
    "runner",
]
