[package]
name = "mirage"
version = "0.1.0"
edition = "2021"

[dependencies]
uart_16550 = "0.3.0"
spin = "0.5.2"
log = "0.4.17"
mirage_abi = { path = "crates/mirage_abi" }

[workspace]
members = [
    # Payloads
    "payloads/csr_ops",
    "payloads/default",
    "payloads/ecall",
    "payloads/mscratch",
    "payloads/csr_id",
    "payloads/pmp",
    "payloads/perf_monitor",
    "payloads/menv_msec",
    "payloads/breakpoint",
    "payloads/mepc",
    "payloads/mcause",
    "payloads/mconfigptr",
    "payloads/tselect",
    "payloads/mret",
    "payloads/misa",

    # Crates
    "crates/mirage_abi",

    # Tooling
    "runner",
]
