# Cargo deny configuration
#
# See https://embarkstudios.github.io/cargo-deny/index.html for reference.

[output]
feature-depth = 1

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-DFS-2016",
]

confidence-threshold = 0.8

[bans]
multiple-versions = "warn"
wildcards = "allow" # Required when using relative path dependencies

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
