# Mirage configuration example
#
# To configure Mirage create a copy of that file named config.toml

[log]
# The default log level
# Possible values are: trace, debug, info, warn, error, off
level = "info"

[debug]
# Maximum number of payload exits before terminating.
# No maximum cap if not present
max_payload_exits = 400

[platform]
# Enable upport for S_mode
# Default to true
s_mode = true
