# Mirage configuration example
#
# To configure Mirage create a copy of that file named config.toml

[log]
# The default log level
# Possible values are: trace, debug, info, warn, error, off
level = "info"

# In addition log levels can be specified for individual modules
#
# Each of the five levels can specify a list of modules which will log all
# message at this or higher priority level. This is useful to selectively log
# low priority messages (e.g. 'trace' or 'debug') while keeping a higher
# default log level (e.g. 'info' or 'warn').
#
# By default only the default log level is taken into account.
trace = ["mirage::virt", "mirage::arch::metal"]
debug = ["mirage::arch"]
info = []
warn = []
error = []

# Use color in logs (using ANSI escape sequences).
# Default to true.
color = true

[debug]
# Maximum number of firmware exits before terminating.
# No maximum cap if not present
max_firmware_exits = 400

[vcpu]
# Enable upport for S_mode
# Default to true
s_mode = true

# Maximum number of PMP exposed to the firmware.
# No maximum by default.
max_pmp = 8
