# Mirage configuration example
#
# To configure Mirage create a copy of that file named config.toml

[log]
# The default log level
# Possible values are: trace, debug, info, warn, error, off
level = "info"

# Use color in logs (using ANSI escape sequences).
# Default to true.
log = true

[debug]
# Maximum number of firmware exits before terminating.
# No maximum cap if not present
max_firmware_exits = 400

[vcpu]
# Enable upport for S_mode
# Default to true
s_mode = true

# Maximum number of PMP exposed to the firmware.
# No maximum by default.
max_pmp = 8
