# Miralis project configuration

## ————————————————————————————— Configurations ————————————————————————————— ##

[config.qemu-virt]
path = "config/test/qemu-virt.toml"

[config.qemu-virt-2harts]
path = "config/test/qemu-virt-2harts.toml"

[config.qemu-virt-release]
path = "config/test/qemu-virt-release.toml"

[config.qemu-virt-sifive-u54]
path = "config/test/qemu-virt-sifive-u54.toml"

[config.qemu-virt-protect-payload]
path = "config/test/qemu-virt-protect-payload.toml"

[config.qemu-virt-keystone]
path = "config/test/qemu-virt-keystone.toml"

[config.qemu-virt-benchmark]
path = "config/test/qemu-virt-benchmark.toml"

[config.spike]
path = "config/test/spike.toml"

[config.spike-protect-payload]
path = "config/test/spike-protect-payload.toml"

[config.spike-benchmark]
path = "./config/test/spike-latency-benchmark.toml"

[config.spike-benchmark-protect-payload]
path = "./config/test/spike-latency-benchmark-protect-payload.toml"


[test.protect-payload-misaligned]
firmware = "misaligned_op"
config = "spike-protect-payload"
description = "Test the protect payload policy emulation of misaligned loads (on Spike)."
