[package]
name = "riscv_pmp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mirage_core = { path = "../core" }
log = { workspace = true }

[features]
