[package]
name = "clint_interrupt"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "clint_interrupt"
path = "main.rs"

[lints]
workspace = true

[dependencies]
miralis_abi = { path = "../../crates/abi" }
test_helpers = { path = "../../crates/test_helpers" }
log = { workspace = true }
