# A simple configuration to run on QEMU virt platform

[log]
level = "info"
color = true

[debug]
# max_firmware_exits = 2000

[vcpu]
max_pmp = 8

[platform]
nb_harts = 1
boot_hart_id = 0

[benchmark]
benchmark_type = "default"
csv_format = true
time = true
instruction = true
nb_exits = true
nb_iter = 10