# A simple configuration to run on QEMU with the Keystone policy

[log]
level = "info"
color = true

[vcpu]
max_pmp = 8

[platform]
nb_harts = 1
boot_hart_id = 0

[benchmark]
enable = false

[policy]
name = "keystone"

[target.miralis]
profile = "dev"
start_address = 0x80000000
stack_size = 0x8000

[target.firmware]
name="opensbi-jump"
profile = "dev"
start_address = 0x80200000

[target.payload]
name = "./images/Image"
profile = "dev"
start_address = 0x80400000
stack_size = 0x80000
