[package]
name = "test-protect-payload-firmware"
version = "0.1.0"
edition = "2024"
license = "MIT"

[[bin]]
name = "test-protect-payload-firmware"
path = "main.rs"

[lints]
workspace = true

[dependencies]
miralis_abi = { path = "../../crates/abi" }
miralis_config = { path = "../../crates/config" }
