[package]
name = "test_payload_lock"
version = "0.1.0"
edition = "2021"

license = "MIT"

[[bin]]
name = "test_payload_lock"
path = "main.rs"

[dependencies]
miralis_abi = { path = "../../crates/abi" }
