[package]
name = "ecall_benchmark"
version = "0.1.0"
edition = "2021"

license = "MIT"

[[bin]]
name = "ecall_benchmark"
path = "main.rs"

[dependencies]
miralis_abi = { path = "../../../crates/abi" }
